### ISSUE TITLE
By Pass Super Admin

### ISSUE THREAD

**Issue by webz2feel** [jeremykenedy/laravel-roles#107]
You've developed very nice package, and i appreciate your work, i'm using your package in my project but i'm facing some problem, The problem is i have to add all permission for super admin too in user_permission table that is not good. Because super admin can access anything without having permission or role in database. So i wanted to ask how i can check this if logged in user is super admin dont check permissions and roles. because i cannot add permission for super admin in table everytime i create new permission. Kindly tell me how i can achieve this. Thanks!

**Comment by jeremykenedy** [comment]
Currently, you have to attach the permissions to that role. Otherwise, you would have to make or modify the middleware to have a bypass based on the role to return true. 

The design is to attach permissions to a role so I do not understand how that is as you say "not good".

The danger about making/modifying a middle to allow that is it may affect a lot of users of the package already.
