### ISSUE TITLE
Use GUI management

### ISSUE THREAD

**Issue by cyrilmanuel** [jeremykenedy/laravel-roles#63]
**First take a look at the following**
1. https://github.com/jeremykenedy/laravel-roles#opening-an-issue 
2. https://github.com/jeremykenedy/laravel-roles/issues?q=is%3Aissue+is%3Aclosed

**Please describe what you are needing help with below:**

hi, 

i have update my .env with this variable to enable GUI. i have 
ROLES_GUI_ENABLED=true
ROLES_GUI_AUTH_ENABLED=true
ROLES_GUI_MIDDLEWARE_ENABLED=true
ROLES_GUI_MIDDLEWARE='role:admin'
ROLES_GUI_CREATE_ROLE_MIDDLEWARE_TYPE='role'
ROLES_GUI_CREATE_ROLE_MIDDLEWARE_TYPE='administrators'
ROLES_GUI_CREATE_PERMISSION_MIDDLEWARE_TYPE='role'
ROLES_GUI_CREATE_PERMISSION_MIDDLEWARE_TYPE='administrators'
ROLES_GUI_BLADE_EXTENDED='layouts.app'
ROLES_GUI_TITLE_EXTENDED='template_title'
ROLES_GUI_LARAVEL_ROLES_ENABLED=false
ROLES_GUI_TOOLTIPS_ENABLED=true
ROLES_GUI_DATATABLES_JS_ENABLED=false

but my question is, can i use your project to manage user, role, permission like your printscreen, without make it from scratch ? 

because when i add this configuration on my .env, i can't acces to the route 127.0.0.1/permissions or anything else in http get. 

i use laravel 5.8.

**Comment by jeremykenedy** [comment]
This package is for roles, permissions, and levels only.

For users management you need to also pull in laravel-users: https://github.com/jeremykenedy/laravel-users

Being unable to access the routes sounds like there may an environment issue.

**Comment by jschalkwijk** [comment]
Hi there, 

I know the issue is closed but I'm experiencing the same problem. I have followed the instructions and had no problems with installing the package.

Things I tried:

I have added the ENV variables to .env and set the `ROLES_GUI_ENABLED=true`. I got 404 not found when trying to access routes. 
I changed the default value inside `config/roles.php` to true. Still no luck. 
I copied your routes to my own routes file and changed the groupo namepace to `'\jeremykenedy\LaravelRoles\App\Http\Controllers\'` (just added the \ so it wouldn't concatenate to my Apps controller namepace ). Then something at last happend. I got this: `'InvalidArgumentException
No hint path defined for [laravelroles].  No hint path defined for [laravelroles].'`
Since I use Laravel 5.8 I initially did not add the namespace to the providers array inside config.app. I tried anyway but this did not resolve the issue.

My .env file works for other variables I use so I doubt that is the problem.

Thanks in advance.

**Comment by jeremykenedy** [comment]
Hello,

I wouldn't recommend overwriting the routes in your web.php. You may want to consider removing those and go with the built calls.

You should publish the config file, update your `.env` file then it should all work out the box. If you are using the laravel-users package you may want to configure that as well.

You may have a jam in your autoloader which can be cleared with `composer dump-autoload`. My first thought is the config and the env are cached in the autoloader.

**Comment by jschalkwijk** [comment]
Thanks for your fast reply, I went fiddling around in the service provider. I just did a plain old `die()`, to check if the SP even got triggerd, it did. So it booted but didn't access the routes. After removing the `if (config('roles.rolesGuiEnabled'))` statement in the boot and register method I could access the routes and everything worked. Apperently the `config() `function takes a key as in a config filename and then a string or array of multiple keys that are in that config file like below:

if (config('roles',['rolesGuiEnabled']))
`if (config('roles','rolesGuiEnabled')) `

If I use one of these inside the RoleServiceProvider it works. I'm curious if other people have the same issue or if it's just me.

**Comment by penguin-herder** [comment]
Very late the the party but I had the same `No hint path defined for [laravelroles]` issue, out of the box, installed on Laravel 8.83.29. so massive thanks @jorn-codes - your comment was a Deus ex machina moment that revealed all!

I had assumed, incorrectly, that it would work out of the box - in short, set .env value ROLES_GUI_ENABLED=true and all was well!

Also, thanks to @jeremykenedy for a nice package. Simple & easy to understand the logic!
